version: '3.8'
services:
  drone_application:
    container_name: drone_application
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo_database
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_database
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=musaladrone
      - SERVER_PORT=9094
    ports:
      - "9095:9095"

  mongo_database:
    image: mongo
    container_name: mongo_database
    restart: always
    ports:
      - "27019:27017"